export const MAIL_TEXT = {
  ko: {
    mail: '메일',
    compose: '메일 쓰기',
    refresh: '새로 고침',
    syncing: '동기화 중',
    searchPlaceholder: '메일 검색...',
    mailList: '메일 목록',
    selectedCount: n => `${n}개 선택됨`,
    count: n => `${n}개`,
    mainMenu: '메인 메뉴로 이동',
    accountSettings: '계정 설정',
    ok: '확인',
    cancel: '취소',
    none: '없음',
    emptyListTitle: '표시할 메일이 없습니다',
    emptyListDesc: label => `${label}에 표시할 메일이 없습니다.`,
    loadingMessages: '메일을 불러오는 중입니다.',
    loadingMore: '더 불러오는 중...',
    selectMailTitle: '메일을 선택하세요',
    selectMailDesc: '선택한 메일의 제목, 보낸 사람, 첨부파일, 본문이 이 영역에 표시됩니다.',
    noSubject: '(제목 없음)',
    noSender: '(보낸 사람 없음)',
    noBody: '본문이 없습니다.',
    from: '보낸 사람',
    to: '받는 사람',
    cc: '참조',
    bcc: '숨은 참조',
    date: '날짜',
    reply: '답장',
    replyAll: '전체 답장',
    forward: '전달',
    sendToAgentic: 'AgenticAI로 보내기',
    summarize: '요약',
    regenerating: '요약 생성 중...',
    regenerate: '요약 다시 생성',
    copySummary: '요약 복사',
    copied: '복사됨',
    copyFailed: '복사에 실패했습니다. 요약 내용을 직접 선택해 복사해주세요.',
    summaryInvalid: '요약 응답 형식이 올바르지 않습니다.',
    summaryFailed: '메일 요약을 생성하지 못했습니다.',
    bodyLoading: '메일 본문을 불러오는 중입니다.',
    attachmentCount: n => `첨부파일 ${n}개`,
    attachmentMark: '첨부파일 있음',
    smartFolders: '스마트 폴더',
    addSmartFolder: '스마트 폴더 추가',
    smartFolderHint: '메일을 여기로 끌어 담으면 계정과 무관하게 모아 볼 수 있어요.',
    folderMissingTitle: '서버에 없는 폴더입니다. 로컬 보관 메일만 표시되며 동기화하지 않습니다.',
    localFolderTitle: '로컬 전용 폴더',
    metaLoading: '메일 계정 정보를 불러오는 중입니다.',
    noAccounts: '연결된 메일 계정이 없습니다.',
    clearSelection: '선택 해제',
    folders: {
      all: '모든 편지함',
      inbox: '받은 편지함',
      starred: '중요 편지함',
      drafts: '임시 보관함',
      search: '검색',
      sent: '보낸 메일',
      trash: '휴지통',
      spam: '스팸 메일함',
    },
    context: {
      delete: '메일 삭제',
      star: '중요 메일로 표시',
      unstar: '중요 메일 표시 해제',
      markUnread: '안읽은 메일로',
      agenticWatch: 'EasyAI가 글타래로 모니터링 하도록 등록',
      registerMailClaw: 'MailClaw에 등록',
      registerMailClawTrash: 'MailClaw 휴지통 이동으로 등록',
      registerAsPost: '게시글로 등록',
      move: '이동',
      noMoveFolders: '이동할 폴더가 없습니다',
    },
    registerAsPost: '게시글로 등록',
    postDialog: {
      title: '게시글로 등록',
      team: 'Team 선택',
      channel: 'Channel 선택',
      post: '게시글 선택',
      newPost: '+ 새로운 게시글로 등록',
      recentHint: '최근 게시글 20개 중에서 선택',
      asComment: '선택한 게시글의 댓글로 등록됩니다.',
      asNewPost: '새 게시글로 등록됩니다.',
      content: '등록할 내용',
      attachments: '함께 등록할 첨부파일',
      attachmentsHint: '메일 첨부파일은 게시글 첨부파일로 복사되어 함께 등록됩니다.',
      register: '등록',
      cancel: '취소',
      registering: '등록 중...',
      loadingPosts: '게시글을 불러오는 중...',
      noTeams: '접근 가능한 팀이 없습니다.',
      noChannels: '채널이 없습니다.',
      noPosts: '최근 게시글이 없습니다.',
      successPost: '새 게시글로 등록했습니다.',
      successComment: '댓글로 등록했습니다.',
      failed: '게시글 등록에 실패했습니다.',
      selectChannelFirst: '팀과 채널을 먼저 선택하세요.',
      emptyContent: '등록할 내용이 비어 있습니다.',
      unknownAuthor: '작성자',
      openOriginalMail: '원본 메일 열기',
      loadingDetail: '메일 본문 불러오는 중...',
    },
    summary: {
      noInfo: '확인된 내용 없음',
      schedule: '일정',
      date: '날짜',
      time: '시간',
      location: '장소',
      participants: '참석 대상',
      notes: '비고',
      keyPoints: '중요 포인트',
      detail: '중요 내용 요약',
      actions: '액션 아이템 / 시간',
      selectDate: '날짜 선택',
      selectTime: '시간 선택',
      allDay: '하루종일',
      savingActionTime: '저장 중',
      calendarAdded: '캘린더 등록됨',
      actionTimeFailed: '액션 아이템 시간을 저장하지 못했습니다.',
    },
    composeView: {
      title: '메일 쓰기',
      cancel: '취소',
      saving: '저장 중',
      draft: '임시 저장',
      sending: '보내는 중',
      send: '보내기',
      fromAccount: '보내는 계정',
      noAccount: '연결된 메일 계정이 없습니다',
      to: '받는 사람',
      cc: '참조',
      bcc: '숨은 참조',
      subject: '제목',
      subjectPlaceholder: '제목을 입력하세요',
      body: '본문',
      attachment: '첨부',
      attachFile: '파일 첨부',
      dropHint: '파일을 이 영역에 끌어다 놓아도 첨부됩니다.',
      needAccount: '보낼 메일 계정을 선택해주세요.',
      needTo: '받는 사람을 입력해주세요.',
      needContent: '제목 또는 본문을 입력해주세요.',
      sent: '메일을 보냈습니다.',
      sendFailed: '메일을 보내지 못했습니다.',
      needDraftAccount: '임시 저장할 메일 계정을 선택해주세요.',
      needDraftContent: '임시 저장할 내용을 입력해주세요.',
      draftSaved: '임시 보관함에 저장했습니다.',
      draftFailed: '임시 저장하지 못했습니다.',
    },
    addressMenu: {
      compose: '메일 작성',
      copy: '주소 복사',
      addContact: '연락처에 추가',
      addVip: 'VIP 목록에 추가',
      search: '해당 주소를 검색',
    },
    folderMenu: {
      add: '폴더 추가',
      addSub: '서브 폴더 추가',
      rename: '이름 변경',
      delete: '폴더 삭제',
      emptyTrash: '휴지통 비우기',
      color: '폴더 색상 설정',
      copyName: '폴더 이름 복사',
      disabledUnified: '통합 폴더는 실제 계정 폴더가 아니라서 이 작업을 직접 적용할 수 없습니다.',
      smartDelete: '스마트 폴더 삭제',
      smartColor: '색상 설정',
      newFolderTitle: '새 폴더',
      newFolderMessage: '새 폴더 이름을 입력하세요.',
      newSubFolderTitle: '서브 폴더',
      newSubFolderMessage: '서브 폴더 이름을 입력하세요.',
      renameFolderTitle: '폴더 이름 변경',
      renameFolderMessage: '폴더의 새 이름을 입력하세요.',
      newSmartFolderTitle: '새 스마트 폴더',
      newSmartFolderMessage: '새 스마트 폴더 이름을 입력하세요.',
      renameSmartFolderTitle: '스마트 폴더 이름 변경',
      renameSmartFolderMessage: '스마트 폴더 이름을 변경합니다.',
    },
    dialogs: {
      emptyTrashTitle: '휴지통 비우기',
      emptyUnifiedTrashTitle: '휴지통 비우기 (모든 계정)',
      emptyTrashMessage: '휴지통에 있는 모든 메일을 영구 삭제합니다.\n\n이 작업은 복구할 수 없습니다.\n\n계속하시겠습니까?',
      emptyUnifiedTrashMessage: n => `모든 계정의 휴지통에 있는 메일을 영구 삭제합니다.${n ? `\n\n대상 계정: ${n}개` : ''}\n\n이 작업은 복구할 수 없습니다.\n\n계속하시겠습니까?`,
    },
    colors: {
      default: '기본값',
      red: '빨강',
      orange: '주황',
      yellow: '노랑',
      green: '녹색',
      blue: '파랑',
      purple: '퍼플',
    },
  },
  en: {
    mail: 'Mail',
    compose: 'Compose',
    refresh: 'Refresh',
    syncing: 'Syncing',
    searchPlaceholder: 'Search mail...',
    mailList: 'Mail list',
    selectedCount: n => `${n} selected`,
    count: n => `${n}`,
    mainMenu: 'Back to main menu',
    accountSettings: 'Account settings',
    ok: 'OK',
    cancel: 'Cancel',
    none: 'None',
    emptyListTitle: 'No mail to display',
    emptyListDesc: label => `No mail to display in ${label}.`,
    loadingMessages: 'Loading mail...',
    loadingMore: 'Loading more...',
    selectMailTitle: 'Select a message',
    selectMailDesc: 'The selected message subject, sender, attachments, and body will appear here.',
    noSubject: '(No subject)',
    noSender: '(No sender)',
    noBody: 'No body content.',
    from: 'From',
    to: 'To',
    cc: 'Cc',
    bcc: 'Bcc',
    date: 'Date',
    reply: 'Reply',
    replyAll: 'Reply all',
    forward: 'Forward',
    sendToAgentic: 'Send to AgenticAI',
    summarize: 'Summarize',
    regenerating: 'Generating summary...',
    regenerate: 'Regenerate summary',
    copySummary: 'Copy summary',
    copied: 'Copied',
    copyFailed: 'Copy failed. Please select and copy the summary manually.',
    summaryInvalid: 'The summary response format is invalid.',
    summaryFailed: 'Failed to generate the mail summary.',
    bodyLoading: 'Loading message body...',
    attachmentCount: n => `${n} attachment${n === 1 ? '' : 's'}`,
    attachmentMark: 'Has attachments',
    smartFolders: 'Smart folders',
    addSmartFolder: 'Add smart folder',
    smartFolderHint: 'Drag mail here to collect it across accounts.',
    folderMissingTitle: 'This folder does not exist on the server. Only local archived mail is shown and it will not sync.',
    localFolderTitle: 'Local-only folder',
    metaLoading: 'Loading mail account information...',
    noAccounts: 'No connected mail accounts.',
    clearSelection: 'Clear selection',
    folders: {
      all: 'All mail',
      inbox: 'Inbox',
      starred: 'Important',
      drafts: 'Drafts',
      search: 'Search',
      sent: 'Sent',
      trash: 'Trash',
      spam: 'Spam',
    },
    context: {
      delete: 'Delete mail',
      star: 'Mark as important',
      unstar: 'Remove important mark',
      markUnread: 'Mark as unread',
      agenticWatch: 'Register thread monitoring with EasyAI',
      registerMailClaw: 'Register in MailClaw',
      registerMailClawTrash: 'Register in MailClaw trash rule',
      registerAsPost: 'Register as post',
      move: 'Move',
      noMoveFolders: 'No folders to move to',
    },
    registerAsPost: 'Register as post',
    postDialog: {
      title: 'Register as post',
      team: 'Select team',
      channel: 'Select channel',
      post: 'Select post',
      newPost: '+ Register as a new post',
      recentHint: 'Choose from the 20 most recent posts',
      asComment: 'It will be added as a comment on the selected post.',
      asNewPost: 'It will be registered as a new post.',
      content: 'Content to register',
      attachments: 'Attachments to include',
      attachmentsHint: 'Mail attachments will be copied and registered with the post.',
      register: 'Register',
      cancel: 'Cancel',
      registering: 'Registering...',
      loadingPosts: 'Loading posts...',
      noTeams: 'No teams available.',
      noChannels: 'No channels available.',
      noPosts: 'No recent posts.',
      successPost: 'Registered as a new post.',
      successComment: 'Registered as a comment.',
      failed: 'Failed to register the post.',
      selectChannelFirst: 'Select a team and channel first.',
      emptyContent: 'The content to register is empty.',
      unknownAuthor: 'Author',
      openOriginalMail: 'Open original mail',
      loadingDetail: 'Loading mail...',
    },
    summary: {
      noInfo: 'No confirmed information',
      schedule: 'Schedule',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      participants: 'Participants',
      notes: 'Notes',
      keyPoints: 'Key points',
      detail: 'Summary',
      actions: 'Action items / Time',
      selectDate: 'Select date',
      selectTime: 'Select time',
      allDay: 'All day',
      savingActionTime: 'Saving',
      calendarAdded: 'Added to calendar',
      actionTimeFailed: 'Failed to save the action item time.',
    },
    composeView: {
      title: 'Compose',
      cancel: 'Cancel',
      saving: 'Saving',
      draft: 'Save draft',
      sending: 'Sending',
      send: 'Send',
      fromAccount: 'From account',
      noAccount: 'No connected mail accounts',
      to: 'To',
      cc: 'Cc',
      bcc: 'Bcc',
      subject: 'Subject',
      subjectPlaceholder: 'Enter a subject',
      body: 'Body',
      attachment: 'Attachments',
      attachFile: 'Attach file',
      dropHint: 'You can also drag files into this area.',
      needAccount: 'Please select a sending account.',
      needTo: 'Please enter a recipient.',
      needContent: 'Please enter a subject or body.',
      sent: 'Mail sent.',
      sendFailed: 'Failed to send mail.',
      needDraftAccount: 'Please select an account for the draft.',
      needDraftContent: 'Please enter content to save as a draft.',
      draftSaved: 'Saved to Drafts.',
      draftFailed: 'Failed to save draft.',
    },
    addressMenu: {
      compose: 'Compose mail',
      copy: 'Copy address',
      addContact: 'Add to contacts',
      addVip: 'Add to VIP list',
      search: 'Search this address',
    },
    folderMenu: {
      add: 'Add folder',
      addSub: 'Add subfolder',
      rename: 'Rename',
      delete: 'Delete folder',
      emptyTrash: 'Empty trash',
      color: 'Folder color',
      copyName: 'Copy folder name',
      disabledUnified: 'This is a unified folder, so this action cannot be applied directly.',
      smartDelete: 'Delete smart folder',
      smartColor: 'Color',
      newFolderTitle: 'New folder',
      newFolderMessage: 'Enter a new folder name.',
      newSubFolderTitle: 'Subfolder',
      newSubFolderMessage: 'Enter a subfolder name.',
      renameFolderTitle: 'Rename folder',
      renameFolderMessage: 'Enter a new folder name.',
      newSmartFolderTitle: 'New smart folder',
      newSmartFolderMessage: 'Enter a new smart folder name.',
      renameSmartFolderTitle: 'Rename smart folder',
      renameSmartFolderMessage: 'Enter a new smart folder name.',
    },
    dialogs: {
      emptyTrashTitle: 'Empty trash',
      emptyUnifiedTrashTitle: 'Empty trash (all accounts)',
      emptyTrashMessage: 'Permanently delete all mail in Trash.\n\nThis action cannot be undone.\n\nContinue?',
      emptyUnifiedTrashMessage: n => `Permanently delete mail in Trash for all accounts.${n ? `\n\nTarget accounts: ${n}` : ''}\n\nThis action cannot be undone.\n\nContinue?`,
    },
    colors: {
      default: 'Default',
      red: 'Red',
      orange: 'Orange',
      yellow: 'Yellow',
      green: 'Green',
      blue: 'Blue',
      purple: 'Purple',
    },
  },
  ja: {
    mail: 'メール',
    compose: 'メール作成',
    refresh: '更新',
    syncing: '同期中',
    searchPlaceholder: 'メール検索...',
    mailList: 'メール一覧',
    selectedCount: n => `${n}件選択中`,
    count: n => `${n}件`,
    mainMenu: 'メインメニューへ戻る',
    accountSettings: 'アカウント設定',
    ok: '確認',
    cancel: 'キャンセル',
    none: 'なし',
    emptyListTitle: '表示するメールがありません',
    emptyListDesc: label => `${label}に表示するメールがありません。`,
    loadingMessages: 'メールを読み込んでいます。',
    loadingMore: 'さらに読み込み中...',
    selectMailTitle: 'メールを選択してください',
    selectMailDesc: '選択したメールの件名、差出人、添付ファイル、本文がここに表示されます。',
    noSubject: '(件名なし)',
    noSender: '(差出人なし)',
    noBody: '本文がありません。',
    from: '差出人',
    to: '宛先',
    cc: 'Cc',
    bcc: 'Bcc',
    date: '日付',
    reply: '返信',
    replyAll: '全員に返信',
    forward: '転送',
    sendToAgentic: 'AgenticAIへ送信',
    summarize: '要約',
    regenerating: '要約生成中...',
    regenerate: '要約を再生成',
    copySummary: '要約をコピー',
    copied: 'コピー済み',
    copyFailed: 'コピーに失敗しました。要約を選択して手動でコピーしてください。',
    summaryInvalid: '要約レスポンスの形式が正しくありません。',
    summaryFailed: 'メール要約を生成できませんでした。',
    bodyLoading: 'メール本文を読み込んでいます。',
    attachmentCount: n => `添付ファイル ${n}件`,
    attachmentMark: '添付ファイルあり',
    smartFolders: 'スマートフォルダ',
    addSmartFolder: 'スマートフォルダ追加',
    smartFolderHint: 'ここにメールをドラッグすると、アカウントに関係なくまとめて表示できます。',
    folderMissingTitle: 'サーバーに存在しないフォルダです。ローカル保管メールのみ表示され、同期されません。',
    localFolderTitle: 'ローカル専用フォルダ',
    metaLoading: 'メールアカウント情報を読み込んでいます。',
    noAccounts: '接続済みのメールアカウントがありません。',
    clearSelection: '選択解除',
    folders: {
      all: 'すべてのメール',
      inbox: '受信トレイ',
      starred: '重要メール',
      drafts: '下書き',
      search: '検索',
      sent: '送信済み',
      trash: 'ゴミ箱',
      spam: '迷惑メール',
    },
    context: {
      delete: 'メール削除',
      star: '重要メールにする',
      unstar: '重要メールを解除',
      markUnread: '未読にする',
      agenticWatch: 'EasyAIでスレッド監視を登録',
      registerMailClaw: 'MailClawに登録',
      registerMailClawTrash: 'MailClawゴミ箱移動に登録',
      registerAsPost: '投稿として登録',
      move: '移動',
      noMoveFolders: '移動先フォルダがありません',
    },
    registerAsPost: '投稿として登録',
    postDialog: {
      title: '投稿として登録',
      team: 'Team を選択',
      channel: 'Channel を選択',
      post: '投稿を選択',
      newPost: '+ 新しい投稿として登録',
      recentHint: '最近の投稿20件から選択',
      asComment: '選択した投稿のコメントとして登録されます。',
      asNewPost: '新しい投稿として登録されます。',
      content: '登録する内容',
      attachments: '一緒に登録する添付ファイル',
      attachmentsHint: 'メールの添付ファイルを投稿の添付ファイルとしてコピーして登録します。',
      register: '登録',
      cancel: 'キャンセル',
      registering: '登録中...',
      loadingPosts: '投稿を読み込んでいます...',
      noTeams: '利用可能なチームがありません。',
      noChannels: 'チャンネルがありません。',
      noPosts: '最近の投稿がありません。',
      successPost: '新しい投稿として登録しました。',
      successComment: 'コメントとして登録しました。',
      failed: '投稿の登録に失敗しました。',
      selectChannelFirst: '先にチームとチャンネルを選択してください。',
      emptyContent: '登録する内容が空です。',
      unknownAuthor: '作成者',
      openOriginalMail: '元のメールを開く',
      loadingDetail: 'メール読み込み中...',
    },
    summary: {
      noInfo: '確認できる内容なし',
      schedule: '日程',
      date: '日付',
      time: '時間',
      location: '場所',
      participants: '参加対象',
      notes: '備考',
      keyPoints: '重要ポイント',
      detail: '重要内容の要約',
      actions: 'アクション項目 / 時間',
      selectDate: '日付を選択',
      selectTime: '時間を選択',
      allDay: '終日',
      savingActionTime: '保存中',
      calendarAdded: 'カレンダー登録済み',
      actionTimeFailed: 'アクション項目の時間を保存できませんでした。',
    },
    composeView: {
      title: 'メール作成',
      cancel: 'キャンセル',
      saving: '保存中',
      draft: '下書き保存',
      sending: '送信中',
      send: '送信',
      fromAccount: '送信アカウント',
      noAccount: '接続済みのメールアカウントがありません',
      to: '宛先',
      cc: 'Cc',
      bcc: 'Bcc',
      subject: '件名',
      subjectPlaceholder: '件名を入力してください',
      body: '本文',
      attachment: '添付',
      attachFile: 'ファイル添付',
      dropHint: 'ファイルをこの領域にドラッグして添付できます。',
      needAccount: '送信するメールアカウントを選択してください。',
      needTo: '宛先を入力してください。',
      needContent: '件名または本文を入力してください。',
      sent: 'メールを送信しました。',
      sendFailed: 'メールを送信できませんでした。',
      needDraftAccount: '下書き保存するアカウントを選択してください。',
      needDraftContent: '下書き保存する内容を入力してください。',
      draftSaved: '下書きに保存しました。',
      draftFailed: '下書きを保存できませんでした。',
    },
    addressMenu: {
      compose: 'メール作成',
      copy: 'アドレスをコピー',
      addContact: '連絡先に追加',
      addVip: 'VIPリストに追加',
      search: 'このアドレスを検索',
    },
    folderMenu: {
      add: 'フォルダ追加',
      addSub: 'サブフォルダ追加',
      rename: '名前変更',
      delete: 'フォルダ削除',
      emptyTrash: 'ゴミ箱を空にする',
      color: 'フォルダ色設定',
      copyName: 'フォルダ名をコピー',
      disabledUnified: '統合フォルダは実際のアカウントフォルダではないため、この操作を直接適用できません。',
      smartDelete: 'スマートフォルダ削除',
      smartColor: '色設定',
      newFolderTitle: '新規フォルダ',
      newFolderMessage: '新しいフォルダ名を入力してください。',
      newSubFolderTitle: 'サブフォルダ',
      newSubFolderMessage: 'サブフォルダ名を入力してください。',
      renameFolderTitle: 'フォルダ名の変更',
      renameFolderMessage: '新しいフォルダ名を入力してください。',
      newSmartFolderTitle: '新規スマートフォルダ',
      newSmartFolderMessage: '新しいスマートフォルダ名を入力してください。',
      renameSmartFolderTitle: 'スマートフォルダ名の変更',
      renameSmartFolderMessage: '新しいスマートフォルダ名を入力してください。',
    },
    dialogs: {
      emptyTrashTitle: 'ゴミ箱を空にする',
      emptyUnifiedTrashTitle: 'ゴミ箱を空にする（全アカウント）',
      emptyTrashMessage: 'ゴミ箱内のすべてのメールを完全に削除します。\n\nこの操作は元に戻せません。\n\n続行しますか？',
      emptyUnifiedTrashMessage: n => `すべてのアカウントのゴミ箱内メールを完全に削除します。${n ? `\n\n対象アカウント: ${n}件` : ''}\n\nこの操作は元に戻せません。\n\n続行しますか？`,
    },
    colors: {
      default: 'デフォルト',
      red: '赤',
      orange: 'オレンジ',
      yellow: '黄',
      green: '緑',
      blue: '青',
      purple: '紫',
    },
  },
}

export function getMailText(language) {
  return MAIL_TEXT[String(language || '').toLowerCase()] || MAIL_TEXT.ko
}
